apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ policy_name }}
  namespace: {{ gl_namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector: {}
    - from:
        - ipBlock:
            cidr: {{ balancer_ip }}
      ports:
        {{ list_ports }}